apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../namespace.yaml
  - ../../postgres.yaml
  - ../../redis.yaml
  - ../../auth-service.yaml
  - ../../api-gateway.yaml
  - ../../qr-generator.yaml
  - ../../sync-receiver.yaml
  - ../../sis-cronjob.yaml
  - ../../monitoring.yaml

namespace: qaat

commonLabels:
  environment: production

configMapGenerator:
  - name: qaat-env-production
    literals:
      - ENVIRONMENT=production
      - LOG_LEVEL=info
      - CORS_ORIGINS=https://admin.qaat.platform,https://student.qaat.platform
